name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build the Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/pix2tex:api -f docker/api.dockerfile .
    
    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/pix2tex:api
